### PR TITLE
Properly authenticate at proxy server

### LINKED ISSUE #636: Proxy connections requiring authentication are failing
**Rally version** (get with `esrally --version`): 1.0.3

**Steps to reproduce**:
 1. Setup an HTTP proxy server that requires authentication
 2. `export http_proxy=http://username:pw@1.2.3.4:8080`
 3. Invoke Rally

**Expected behavior**: 

Rally uses the proxy to connect to the Internet

**Actual behavior**: 

Rally reports that no Internet connection is available. On the command line we can see.

```
[WARNING] No Internet connection detected. Automatic download of track data sets etc. is disabled. 
```

**Provide logs (if relevant)**:

```
2019-01-23 15:19:43,262 -not-actor-/PID:16740 esrally.utils.net INFO Rally connects via proxy URL [http://username:pw@1.2.3.4:8080] to the Internet (picked up from the environment variable [http_proxy]).
2019-01-23 15:19:43,263 -not-actor-/PID:16740 esrally.utils.net DEBUG Checking for internet connection against [https://github.com/]
2019-01-23 15:19:43,347 -not-actor-/PID:16740 esrally.utils.net DEBUG Could not detect a working Internet connection
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "/usr/local/python3/lib/python3.6/site-packages/urllib3/connection.py", line 294, in connect
    self._tunnel()
  File "/usr/local/python3/lib/python3.6/http/client.py", line 919, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 407 Proxy Authentication Required
```

**Analysis**:

The problem is that Python does not take the provided credentials in the URL into account. Thus, Rally needs to provide them separately using a [ProxyBasicAuthHandler](https://docs.python.org/3/library/urllib.request.html#urllib.request.ProxyBasicAuthHandler).

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit Rally will set the proper authentication header for
proxies that require it.

Closes #636

### CODE REVIEW

**Comment by dliappis** [comment]
I am documenting how I tested this, in case we want to add an integration test later on for similar stuff:

```
cat >squid.conf <<EOF
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/squidpasswords
auth_param basic realm proxy
acl authenticated proxy_auth REQUIRED
http_access allow authenticated
http_port 3128
EOF
```

Created a `squidpasswords` file using `htpasswd -c squidpasswords testuser` username `testuser` and password `testuser` with the following content:

```
cat >squidpasswords <<EOF
cat squidpasswords
testuser:$apr1$WQMVypS2$vUzNTPn6tKhTrRZP16/li.
EOF
```

and run:

```
docker run --rm --name squid -d -v $PWD/squidpasswords:/etc/squid/squidpasswords -v $PWD/squid.conf:/etc/squid/squid.conf -p 3128:3128 datadog/squid
```

and to see access logs:

```
docker exec -ti squid tail -f /var/log/squid/access.log
```

On the Rally side I first set:

```
export http_proxy=http://testuser:testuser@127.0.0.1:3128
```

Using current Rally master commit:

```
esrally --distribution-version=6.6.0 --track="geonames" --track-params="ingest_percentage:15" --challenge="append-no-conflicts-index-only"
```

shows on the squid log:

```
1550851149.662      0 172.17.0.1 TCP_DENIED/407 3871 CONNECT github.com:443 - HIER_NONE/- text/html
1550851149.665      0 172.17.0.1 TCP_DENIED/407 3871 CONNECT github.com:443 - HIER_NONE/- text/html
1550851149.667      0 172.17.0.1 TCP_DENIED/407 3871 CONNECT github.com:443 - HIER_NONE/- text/html
1550851149.668      0 172.17.0.1 TCP_DENIED/407 3871 CONNECT github.com:443 - HIER_NONE/- text/html
```

plus of course Rally itself reports:

```
[WARNING] No Internet connection detected. Automatic download of track data sets etc. is disabled.
```

Using this PR with the same Rally command, squid log shows:

```
1550851566.691  60860 172.17.0.1 TCP_TUNNEL/200 86897 CONNECT github.com:443 testuser HIER_DIRECT/192.30.253.112 -
```

and the warning is gone from the Rally output.

**Comment by danielmitterdorfer** [comment]
@dliappis great writeup! I have added integration tests now in https://github.com/elastic/rally/pull/652/commits/421f07cc4babe211ad9e7b4697d5bf1389976a8d based on your comment. Can you please have another look?

File: integration-test.sh [hunk 1]
```diff
@@ -134,7 +135,46 @@ function set_up {
...
-    popd
+    popd > /dev/null
+}
+
+function set_up_proxy_server {
+    # we want to see output to stderr for diagnosing problems
+    if docker ps > /dev/null; then
+        info "Docker is available. Proxy-related tests will be run"
+        # Portably create a temporary config directory for Squid on Linux or MacOS
+        local config_dir=$(mktemp -d 2>/dev/null || mktemp -d -t 'tmp_squid_cfg')
```
Comment (danielmitterdorfer) [inline integration-test.sh]: For Docker on MacOS this requires to (manually) add `/var/folders` to the list of allowed paths (otherwise Docker will complain that it can't bind-mount the directory). `/var/folders` is actually symlinked to `/private/var/folders` and `/private` is already configured (recursively) for Docker but not `/var/folders` is not. I think we should add this to our developer docs. Wdyt?

Comment (danielmitterdorfer) [reply integration-test.sh]: As discussed via another channel we'll instead use an already existing directory tree that we use for integration tests anyway. I'll push a new commit addressing this.
